name: Lint GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color -ignore SC2129 -ignore SC2086
